### ISSUE TITLE
Auto enable browser and buy token on Mobile iOS

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Static-Content#1]
- Find api get app version
- Setup github action cron job auto detect new app version

**Comment by nguyenduythuc** [comment]
This issue doesn't have pull request and was fixed in repo https://github.com/Koniverse/SubWallet-Static-Content, [cron-check-new-release.yml](https://github.com/Koniverse/SubWallet-Static-Content/blob/main/.github/workflows/cron-check-new-release.yml)
